/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/N1fJJxPJHiM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { SVGProps } from "react";
import { Button } from "./ui/button";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function DeleteButton({ onClick }: { onClick: () => void }) {
  return (
    <Button onClick={onClick} className="bg-black text-white">
      <TrashIcon className="mr-2 h-4 w-4" />
      Delete
    </Button>
  );
}

function TrashIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  );
}