/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/04bar4OKkzn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/import { Button } from "@/components/ui/button";
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { SelectValue, SelectTrigger, SelectLabel, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select";

export function Reservation() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100">
      <div className="max-w-2xl mx-auto p-6 sm:p-8 bg-white text-black">
      <h1 className="text-3xl font-bold mb-6">Reserve Sport Equipment</h1>
      <form className="space-y-6">
        <div>
          <label className="block font-medium mb-1" htmlFor="date">
            Date of Reservation
          </label>
          <Popover>
            <PopoverTrigger asChild>
              <Button className="w-full justify-start text-left font-normal bg-white text-black border-black" id="date" variant="outline">
                <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start" className="w-auto p-0 bg-white text-black">
              <Calendar mode="single" />
            </PopoverContent>
          </Popover>
        </div>
        <div>
          <label className="block font-medium mb-1">Equipment</label>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {/* Add your equipment input fields here */}
          </div>
        </div>
        <div>
          <label className="block font-medium mb-1" htmlFor="installers">
            Installers
          </label>
          <Select>
            <SelectTrigger className="w-full bg-white text-black border-black">
              <SelectValue placeholder="Select installers" />
            </SelectTrigger>
            <SelectContent className="bg-white text-black">
              <SelectGroup>
                <SelectLabel>Available Installers</SelectLabel>
                <SelectItem value="installer1">Installer 1</SelectItem>
                <SelectItem value="installer2">Installer 2</SelectItem>
                <SelectItem value="installer3">Installer 3</SelectItem>
                <SelectItem value="installer4">Installer 4</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
        </div>
        <Button className="w-full bg-black text-white" type="submit">
          Reserve
        </Button>
      </form>
    </div>

    </div>
    
  );
}

function CalendarDaysIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="text-black"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}
